apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: For testing you local change you could uncomment and override the following
# images:
# - name: quay.io/spotahome/redis-operator
#   newName: your-repo/redis-operator
#   newTag: your-tag

images:
- name: quay.io/spotahome/redis-operator
  newName: samof76/redis-operator
  newTag: d51a76e4bcdbf1cba50aecc1e991b834cf10e06c

resources:
- "rolebinding.yaml"
- "roles.yaml"
- "operator.yaml"
- "serviceaccount.yaml"

namespace: redis-failover